/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paymentsystem;

import dbConnect.DB_connect;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author RPA_Virtusa
 */
public class AdminAprove extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form AdminAprove
     */
    public AdminAprove() throws SQLException {
        initComponents();
        conn = DB_connect.connect();
        tableLoad();

    }
    public void tableLoad() {
        try {
            String sqlQuery = "SELECT * FROM `holidayaprovetable`";
            pst = conn.prepareStatement(sqlQuery);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    void updateApproveTable(String ID,String Date,String Status)
    {
            String CurrentStatusQuary = "UPDATE `finaleholidaystatustable` SET  `AdminStatus` = '"+Status+"' where `MemberID`= '" + ID + "' and `Date`='"+Date+"'";
            
        try {
            //String CurrentStatusQuaryForHoliday = "UPDATE `currentstatus` SET  `CurrentStatus` = 'OnTime' where `memberName`= '" + memberName + "'";
            pst = conn.prepareStatement(CurrentStatusQuary);
              pst.execute(); 
              JOptionPane.showMessageDialog(null,"successfully "+Status+" the status");
        } catch (SQLException ex) {
            Logger.getLogger(AdminAprove.class.getName()).log(Level.SEVERE, null, ex);
        }
            //JOptionPane.showMessageDialog(null," New Member Added Successfully123.......!!!");
            //System.out.println(getgender());
           // JOptionPane.showMessageDialog(null, " good Morning  " + memberName + "");
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txt_MemberName = new javax.swing.JTextField();
        txt_MemberID = new javax.swing.JTextField();
        txt_Date = new javax.swing.JTextField();
        cmb_HolidayType = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        setMaximumSize(new java.awt.Dimension(900, 660));
        setMinimumSize(new java.awt.Dimension(900, 660));
        setPreferredSize(new java.awt.Dimension(900, 660));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 70, 720, 240);
        jPanel1.add(txt_MemberName);
        txt_MemberName.setBounds(190, 340, 120, 26);
        jPanel1.add(txt_MemberID);
        txt_MemberID.setBounds(50, 340, 120, 26);
        jPanel1.add(txt_Date);
        txt_Date.setBounds(330, 340, 120, 26);

        cmb_HolidayType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Approved", "NotApproved", "Pending" }));
        jPanel1.add(cmb_HolidayType);
        cmb_HolidayType.setBounds(470, 340, 120, 26);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 90, 800, 390);
        jPanel1.setBackground(new Color(0,0,10,130));

        jPanel2.setLayout(null);

        jButton1.setText("Update and Aprove");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(310, 30, 130, 50);

        jButton2.setText("aprove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(80, 30, 90, 50);

        jButton3.setText("Not Aprove");
        jPanel2.add(jButton3);
        jButton3.setBounds(180, 30, 90, 50);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(50, 510, 800, 110);
        jPanel2.setBackground(new Color(0,0,10,130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Register.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-36, -16, 1000, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            int selectedRowIndex = jTable1.getSelectedRow();
            txt_MemberID.setText(model.getValueAt(selectedRowIndex, 1).toString());
            txt_MemberName.setText(model.getValueAt(selectedRowIndex, 2).toString());
            txt_Date.setText(model.getValueAt(selectedRowIndex, 3).toString());
            cmb_HolidayType.setSelectedItem(model.getValueAt(selectedRowIndex, 5).toString());
            
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        updateApproveTable(txt_MemberID.getText(),txt_Date.getText(),"Approved");
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAprove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAprove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAprove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAprove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AdminAprove().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AdminAprove.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmb_HolidayType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_Date;
    private javax.swing.JTextField txt_MemberID;
    private javax.swing.JTextField txt_MemberName;
    // End of variables declaration//GEN-END:variables
}
