/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paymentsystem;

import dbConnect.DB_connect;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author RPA_Virtusa
 */
public class adminSettings extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form adminSettings
     */
    public adminSettings() throws SQLException {
        initComponents();
        conn = DB_connect.connect();
    }
    
    Boolean checkUserNameAndPassword(String user, String pass)
    {
    
          try {
            String sql = "SELECT * FROM `admintable` WHERE `userName`='"+user+"' and `passWord`='"+pass+"'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery(sql);

            while (rs.next()) {
    return true;
            }
        } catch (Exception e) {
        }
    return false;
            
   }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CurrentUserName = new javax.swing.JTextField();
        NewUserName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        currentPassword = new javax.swing.JPasswordField();
        NewPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel2.setForeground(new java.awt.Color(51, 255, 255));
        jLabel2.setText("New Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(290, 100, 100, 14);

        jLabel3.setForeground(new java.awt.Color(51, 255, 255));
        jLabel3.setText("New UserName");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(290, 40, 100, 40);

        jLabel4.setForeground(new java.awt.Color(51, 255, 255));
        jLabel4.setText("Current Password");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 100, 100, 14);

        jLabel5.setForeground(new java.awt.Color(51, 255, 255));
        jLabel5.setText("Current UserName");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 40, 110, 40);
        jPanel1.add(CurrentUserName);
        CurrentUserName.setBounds(140, 50, 120, 26);
        jPanel1.add(NewUserName);
        NewUserName.setBounds(390, 50, 120, 26);

        jButton1.setText("Change Settings");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(200, 190, 120, 30);

        currentPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(currentPassword);
        currentPassword.setBounds(140, 93, 120, 26);
        jPanel1.add(NewPassword);
        NewPassword.setBounds(390, 93, 120, 26);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 120, 530, 320);
        jPanel1.setBackground(new Color(0,0,10,130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Register.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-36, -26, 930, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          String cUser = CurrentUserName.getText();
          String nUser = NewUserName.getText();
          String cPass = currentPassword.getText();
          String nPass = NewPassword.getText();
          if(checkUserNameAndPassword(cUser,cPass))
          {
                  try {
            String searchQuary = "UPDATE `admintable` SET `userName`='"+nUser+"' ,`passWord`='"+nPass+"' WHERE `userName` ='"+cUser+"'";
            pst = conn.prepareStatement(searchQuary);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Username and password changed successfully");   
        } catch (Exception e) {
            System.out.println(e);
        }
        
          }
          else
          {
            JOptionPane.showMessageDialog(null,"Current username or Current password is not match", "Error", JOptionPane.ERROR_MESSAGE);
          
          }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void currentPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new adminSettings().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(adminSettings.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CurrentUserName;
    private javax.swing.JPasswordField NewPassword;
    private javax.swing.JTextField NewUserName;
    private javax.swing.JPasswordField currentPassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
