/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paymentsystem;

//import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import dbConnect.DB_connect;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author RPA_Virtusa
 */
public class dailyUpdateEdit extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form dailyUpdateEdit
     */
    public dailyUpdateEdit() throws SQLException {
        initComponents();
        conn = DB_connect.connect();
        tableLoad();
        txt_AutoId.setEnabled(false);
        txt_Mid.setEnabled(false);
        txt_Mname.setEnabled(false);
        loadDateCombo();
        loadNameCombo() ;
        seticon();
    }
    void loadNameCombo() {
        try {
            String sql = "SELECT * FROM `memberdetails`";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery(sql);

            while (rs.next()) {
                String name = rs.getString("memberName");
                cmb_memberName.addItem(name);
                //cmb_memberName.addItem(name);
            }
        } catch (Exception e) {
        }

    }
    
       void loadDateCombo() {
        Calendar now = Calendar.getInstance();   
        int year = now.get(Calendar.YEAR);
        cmb_yearmonth.addItem(year + "-01");
        cmb_yearmonth.addItem(year + "-02");
        cmb_yearmonth.addItem(year + "-03");
        cmb_yearmonth.addItem(year + "-04");
        cmb_yearmonth.addItem(year + "-05");
        cmb_yearmonth.addItem(year + "-06");
        cmb_yearmonth.addItem(year + "-07");
        cmb_yearmonth.addItem(year + "-08");
        cmb_yearmonth.addItem(year + "-09");
        cmb_yearmonth.addItem(year + "-10");
        cmb_yearmonth.addItem(year + "-11");
        cmb_yearmonth.addItem(year + "-12");

    }
  public void tableLoad(){
        try {
            String sqlQuery = "SELECT * FROM `dailystatus`";
            pst = conn.prepareStatement(sqlQuery);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            System.out.println(e);
        }
    }
  
   public void tableLoadTosearch(){
        try {
            String sqlQuery = "SELECT * FROM `dailystatus`";
            pst = conn.prepareStatement(sqlQuery);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txt_Mid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmb_Status = new javax.swing.JComboBox();
        txt_AutoId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_Mdate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_Time = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmb_memberName = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lbl_AutoId = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_Mname = new javax.swing.JTextField();
        cmb_yearmonth = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 700));
        setMinimumSize(new java.awt.Dimension(800, 700));
        setPreferredSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 60, 630, 240);
        jPanel1.add(txt_Mid);
        txt_Mid.setBounds(350, 330, 130, 26);

        jLabel3.setText("Search");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 10, 60, 20);

        cmb_Status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OnTime", "PauseTime", "ResumeTime", "OffTime" }));
        jPanel1.add(cmb_Status);
        cmb_Status.setBounds(350, 430, 130, 26);
        jPanel1.add(txt_AutoId);
        txt_AutoId.setBounds(100, 340, 130, 26);

        jLabel4.setForeground(new java.awt.Color(51, 255, 255));
        jLabel4.setText("Member Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 390, 90, 14);
        jPanel1.add(txt_Mdate);
        txt_Mdate.setBounds(100, 430, 130, 26);

        jLabel5.setForeground(new java.awt.Color(51, 255, 255));
        jLabel5.setText("Status");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(280, 430, 60, 20);
        jPanel1.add(txt_Time);
        txt_Time.setBounds(350, 380, 130, 26);

        jLabel6.setForeground(new java.awt.Color(51, 255, 255));
        jLabel6.setText("Time");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(290, 390, 60, 14);

        cmb_memberName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_memberNameActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_memberName);
        cmb_memberName.setBounds(70, 10, 130, 26);

        jLabel7.setForeground(new java.awt.Color(51, 255, 255));
        jLabel7.setText("Date");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 440, 60, 14);

        jButton1.setText("D");
        jPanel1.add(jButton1);
        jButton1.setBounds(570, 380, 60, 40);

        jButton2.setText("S");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(500, 10, 60, 30);

        lbl_AutoId.setForeground(new java.awt.Color(51, 255, 255));
        jPanel1.add(lbl_AutoId);
        lbl_AutoId.setBounds(110, 340, 60, 0);

        jLabel9.setForeground(new java.awt.Color(51, 255, 255));
        jLabel9.setText("Member ID");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(280, 340, 60, 14);

        jLabel10.setForeground(new java.awt.Color(51, 255, 255));
        jLabel10.setText("Auto ID");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 340, 60, 14);
        jPanel1.add(txt_Mname);
        txt_Mname.setBounds(100, 380, 130, 26);

        cmb_yearmonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Date" }));
        jPanel1.add(cmb_yearmonth);
        cmb_yearmonth.setBounds(270, 10, 160, 26);

        jButton3.setText("U");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(570, 330, 60, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 80, 680, 500);
        jPanel1.setBackground(new Color(0,0,10,130));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        jButton6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 255, 255), new java.awt.Color(0, 255, 255), new java.awt.Color(0, 255, 255), new java.awt.Color(0, 255, 255)));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(690, 20, 50, 50);

        jLabel2.setFont(new java.awt.Font("Constantia", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Edit Daily Updates");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 20, 440, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Register.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-50, -120, 1000, 1110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
           int selectedRowIndex = jTable1.getSelectedRow();
            txt_AutoId.setText(model.getValueAt(selectedRowIndex, 0).toString());
            txt_Mid.setText(model.getValueAt(selectedRowIndex, 1).toString());
            txt_Mname.setText(model.getValueAt(selectedRowIndex, 2).toString());
            txt_Mdate.setText(model.getValueAt(selectedRowIndex, 3).toString());
            txt_Time.setText(model.getValueAt(selectedRowIndex, 4).toString());
            cmb_Status.setSelectedItem(model.getValueAt(selectedRowIndex, 5).toString());
        
            

    }//GEN-LAST:event_jTable1MouseClicked

    private void cmb_memberNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_memberNameActionPerformed
        // TODO add your handling code here:
       /* 
         DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
         String SearchItem = cmb_memberName.getSelectedItem().toString();
         TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
         jTable1.setRowSorter(tr);
        */
        
    }//GEN-LAST:event_cmb_memberNameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String date= cmb_yearmonth.getSelectedItem().toString();
        String name= cmb_memberName.getSelectedItem().toString();
             try {
            String searchQuary = "SELECT * FROM `dailystatus` WHERE `MemberName` ='"+name+"' and `Date`  LIKE '" + date + "%'";
            pst = conn.prepareStatement(searchQuary);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String autoID = txt_AutoId.getText();
         String memberID = txt_Mid.getText();
          String memberName = txt_Mname.getText();
           String time = txt_Time.getText();
            String date = txt_Mdate.getText();
             String status = cmb_Status.getSelectedItem().toString();
             
                 try {
            String searchQuary = "UPDATE `dailystatus` SET `MemberId`='"+memberID+"',`MemberName`='"+memberName+"',`Date`='"+date+"',`Time`='"+time+"',`Status`='"+status+"'  WHERE `AutoID`='"+autoID+"'";
            pst = conn.prepareStatement(searchQuary);
            pst.execute();
            JOptionPane.showMessageDialog(null,date+" "+memberName+"'s"+ "record updated successfully");
            tableLoad();
        } catch (Exception e) {
            System.out.println(e);
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        HomePage h1 =new HomePage();
        h1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dailyUpdateEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dailyUpdateEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dailyUpdateEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dailyUpdateEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new dailyUpdateEdit().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(dailyUpdateEdit.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmb_Status;
    private javax.swing.JComboBox cmb_memberName;
    private javax.swing.JComboBox cmb_yearmonth;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_AutoId;
    private javax.swing.JTextField txt_AutoId;
    private javax.swing.JTextField txt_Mdate;
    private javax.swing.JTextField txt_Mid;
    private javax.swing.JTextField txt_Mname;
    private javax.swing.JTextField txt_Time;
    // End of variables declaration//GEN-END:variables

   private void seticon() {
     setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("madIcon1_1.jpg")));
    }
}
