/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
 //Randima Senanayake
package paymentsystem;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import dbConnect.DB_connect;
import java.sql.Date;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP1
 */
public class memberRegistration extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    java.sql.Date sqldate;

    /**
     * Creates new form memberRegistration
     */
    public memberRegistration() throws SQLException {
        initComponents();
        conn = DB_connect.connect();
        showUser();
    }

    public void showUser(){
    User currentUser = new User();
    String cUser = currentUser.getUserName();
    lbl_username.setText(cUser);
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        lbl_MemberID = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_ContactNumber = new javax.swing.JTextField();
        txt_MemberID = new javax.swing.JTextField();
        dc_JoningDate = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_MemberName = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(30, 50, 520, 170);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 255));
        jLabel3.setText("Search");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(70, 10, 60, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Member ID", "Member Name" }));
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(130, 10, 140, 26);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(90, 430, 590, 230);
        jPanel2.setBackground(new Color(0,0,10,130));

        jPanel1.setLayout(null);

        lbl_MemberID.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lbl_MemberID.setForeground(new java.awt.Color(153, 255, 255));
        lbl_MemberID.setText("Member ID");
        jPanel1.add(lbl_MemberID);
        lbl_MemberID.setBounds(20, 20, 80, 30);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 255));
        jLabel5.setText("Member Name");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 60, 100, 30);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 255));
        jLabel6.setText("Joining Date");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 100, 100, 30);
        jPanel1.add(txt_ContactNumber);
        txt_ContactNumber.setBounds(140, 140, 310, 26);

        txt_MemberID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MemberIDActionPerformed(evt);
            }
        });
        jPanel1.add(txt_MemberID);
        txt_MemberID.setBounds(140, 20, 310, 26);

        dc_JoningDate.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(dc_JoningDate);
        dc_JoningDate.setBounds(140, 100, 310, 26);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rset-01-128.png"))); // NOI18N
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jButton1);
        jButton1.setBounds(500, 240, 42, 42);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-Add-icon.png"))); // NOI18N
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(500, 30, 42, 42);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update128.png"))); // NOI18N
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jButton3);
        jButton3.setBounds(500, 100, 42, 42);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete128.png"))); // NOI18N
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jButton4);
        jButton4.setBounds(500, 170, 42, 42);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 255));
        jLabel4.setText("Fixed Hours");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 260, 110, 30);
        jPanel1.add(txt_MemberName);
        txt_MemberName.setBounds(140, 60, 310, 26);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(140, 260, 310, 26);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(140, 180, 310, 26);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(140, 220, 310, 26);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 255, 255));
        jLabel8.setText("Contact Number");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 140, 110, 30);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 255, 255));
        jLabel9.setText("Per Normal Hour");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 180, 110, 30);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 255, 255));
        jLabel10.setText("Per OT Hour");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 220, 110, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(90, 90, 590, 320);
        jPanel1.setBackground(new Color(0,0,10,130));

        jLabel2.setFont(new java.awt.Font("Constantia", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Member Registration Form");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 20, 630, 50);
        getContentPane().add(lbl_username);
        lbl_username.setBounds(720, 30, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Register.jpg"))); // NOI18N
        jLabel1.setLabelFor(this);
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 0, 1150, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String memberID = txt_MemberID.getText();
        String memberName = txt_MemberName.getText();
        //  String joinDate = dc_JoningDate.getText();
        Calendar calendar = Calendar.getInstance();

        java.sql.Date joinDateObject = new java.sql.Date(dc_JoningDate.getDate().getTime());
        String contactNumber = txt_ContactNumber.getText();
        System.out.println("Date : " + joinDateObject);
        try {
            String NewMemberInsertQuary = "INSERT INTO `memberdetails`(`memberId`, `memberName`, `joinDate`, `contactNumber`) VALUES ('" + memberID + "','" + memberName + "','" + joinDateObject + "','" + contactNumber + "')";
            pst = conn.prepareStatement(NewMemberInsertQuary);
            //JOptionPane.showMessageDialog(null," New Member Added Successfully123.......!!!");
            pst.execute();   //System.out.println(getgender());
            JOptionPane.showMessageDialog(null, " New Member Added Successfully.......!!!");
        } catch (Exception e) {
            System.out.println(e);
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_MemberIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MemberIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MemberIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(memberRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(memberRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(memberRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(memberRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new memberRegistration().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(memberRegistration.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dc_JoningDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lbl_MemberID;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JTextField txt_ContactNumber;
    private javax.swing.JTextField txt_MemberID;
    private javax.swing.JTextField txt_MemberName;
    // End of variables declaration//GEN-END:variables
}
