/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paymentsystem;

import dbConnect.DB_connect;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author User
 */
public class unitPayment extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rst = null;
    
    /**
     * Creates new form unitPayment
     */
    public unitPayment() throws SQLException {
        initComponents();
        conn = DB_connect.connect();
        tableLoad();
    }

    public void tableLoad(){
        try {
            String sqlQuery = "SELECT * FROM `unitpayment`";
            pst = conn.prepareStatement(sqlQuery);
            rst = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rst));
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_memid = new javax.swing.JTextField();
        txt_memname = new javax.swing.JTextField();
        txt_NormalHour = new javax.swing.JTextField();
        txt_OtHour = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        dc_ChangedDate = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 700));
        setMinimumSize(new java.awt.Dimension(800, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "No of hours", "Rate per hour", "Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 20, 510, 190);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(120, 430, 570, 230);
        jPanel1.setBackground(new Color(0,0,10,130));

        jPanel2.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 255, 255));
        jLabel7.setText("Memeber ID");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(30, 30, 73, 17);

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 255, 255));
        jLabel8.setText("Member Name");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 70, 87, 17);

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 255, 255));
        jLabel9.setText("Per Normal Hour");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(30, 120, 98, 17);

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 255, 255));
        jLabel10.setText("Per OT Hour");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(30, 170, 90, 17);

        txt_memid.setToolTipText("");
        txt_memid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_memidActionPerformed(evt);
            }
        });
        jPanel2.add(txt_memid);
        txt_memid.setBounds(170, 20, 288, 26);
        jPanel2.add(txt_memname);
        txt_memname.setBounds(170, 70, 288, 26);
        jPanel2.add(txt_NormalHour);
        txt_NormalHour.setBounds(170, 120, 288, 26);
        jPanel2.add(txt_OtHour);
        txt_OtHour.setBounds(170, 170, 288, 26);

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 255, 255));
        jLabel11.setText("Date");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(30, 220, 78, 17);

        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button-Add-icon.png"))); // NOI18N
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel2.add(btn_add);
        btn_add.setBounds(220, 260, 42, 42);

        dc_ChangedDate.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(dc_ChangedDate);
        dc_ChangedDate.setBounds(170, 210, 290, 26);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(120, 80, 570, 320);
        jPanel2.setBackground(new Color(0,0,10,130));

        jLabel2.setFont(new java.awt.Font("Constantia", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Unit Payment Settings Form");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 20, 700, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Register.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 840, 820);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        String id = txt_memid.getText();
        String name = txt_memname.getText();
        double normalHour = Double.parseDouble(txt_NormalHour.getText());
        double OtHour = Double.parseDouble(txt_OtHour.getText());
        java.sql.Date date = new java.sql.Date(dc_ChangedDate.getDate().getTime());
        
        try{
        String paymentUnit = "INSERT INTO `unitpayment`(`MemberID`, `MemberName`,`date`,`ratePerOtHour`,`ratePerNormalHour`) "
                + "VALUES ('"+id+"','"+name+"','"+date+"','"+normalHour+"','"+OtHour+"')";
                      
        pst = conn.prepareStatement(paymentUnit);
        pst.execute();
        JOptionPane.showMessageDialog(null," New Member Added Successfully.......!!!");
        tableLoad();
        } catch (Exception e) {
            System.out.println(e);
        }           
    }//GEN-LAST:event_btn_addActionPerformed

    private void txt_memidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_memidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_memidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(unitPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(unitPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(unitPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(unitPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new unitPayment().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(unitPayment.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private com.toedter.calendar.JDateChooser dc_ChangedDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_NormalHour;
    private javax.swing.JTextField txt_OtHour;
    private javax.swing.JTextField txt_memid;
    private javax.swing.JTextField txt_memname;
    // End of variables declaration//GEN-END:variables
}
